interface Slot {
  id: string,
  column: string,
  _id: string,
  title: string,
  speaker: string,
  notes: string,
  startType: string,
  startTime: string,
  duration: string,
  appearance: string,
  message: string,
  warningTime: string,
  dangerTime: string,
  warningColor: string,
  dangerColor: string,
  warningSound: string,
  dangerSound: string,
  flash: boolean,
  flashCount: number,
  sortOrder: number,
  status: string,
  startCountAt: string,
  active: boolean,
  eventId: string
}

let slot: Slot = {
  id: "1",
  column: "backlog",
  _id: '1',
  title: 'Slot 1',
  speaker: 'Speaker 1',
  notes: 'Some notes',
  startType: 'Scheduled',
  startTime: '1719322922659',
  duration: '120',
  appearance: 'default',
  message: 'Message',
  warningTime: '10',
  dangerTime: '5',
  warningColor: 'yellow',
  dangerColor: 'red',
  warningSound: 'warning',
  dangerSound: 'danger',
  flash: false,
  flashCount: 3,
  sortOrder: 1,
  status: 'active',
  startCountAt: 'start',
  active: false,
  eventId: '1'
}

export default [{...slot, id: '1'}, {...slot, id: '2'}, {...slot, id: '3'}]